openapi: 3.0.3
info:
  title: jdevtree Auth API
  description: Authentication microservice for jdevtree. Supports GitHub OAuth and
    local JWT auth flows.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /auth/oauth/github:
    post:
      summary: Login with GitHub
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseBean'
        '500': &id001
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                internalError:
                  summary: Server error
                  value:
                    code: INTERNAL_SERVER_ERROR
                    message: Unexpected error occurred
                    data: null
        '400':
          description: Invalid GitHub code or redirect URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidCode:
                  summary: Invalid GitHub code
                  value:
                    code: INVALID_GITHUB_CODE
                    message: The provided GitHub code is invalid or expired
                    data: null
        '403':
          description: GitHub authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                githubUnauthorized:
                  summary: Unauthorized GitHub request
                  value:
                    code: GITHUB_UNAUTHORIZED
                    message: Your GitHub request was unauthorized
                    data: null
  /auth/oauth/github/link:
    post:
      summary: Link GitHub account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: GitHub linked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseBean'
        '500': *id001
        '400':
          description: GitHub account already linked or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                githubLinkFail:
                  summary: GitHub already linked or missing JWT
                  value:
                    code: GITHUB_ALREADY_LINKED
                    message: This GitHub account is already linked
                    data: null
        '401':
          description: Unauthorized - JWT missing or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                unauthorized:
                  summary: JWT missing or invalid
                  value:
                    code: UNAUTHORIZED
                    message: Authentication token is missing or invalid
                    data: null
  /auth/refresh:
    post:
      summary: Refresh access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: Token refreshed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseBean'
        '500': *id001
        '400':
          description: Missing or malformed refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidRefresh:
                  summary: Refresh token missing or invalid
                  value:
                    code: INVALID_REFRESH_TOKEN
                    message: The refresh token is invalid or malformed
                    data: null
        '403':
          description: Refresh token has been reused or blacklisted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                reusedToken:
                  summary: Refresh token reused
                  value:
                    code: REFRESH_TOKEN_REUSED
                    message: This refresh token has already been used or is blacklisted
                    data: null
  /auth/logout:
    post:
      summary: Logout and revoke tokens
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'
              examples:
                success:
                  summary: Successful logout
                  value:
                    code: SUCCESS
                    message: Logout successful
                    data:
                      status: logged_out
        '500': *id001
        '401':
          description: JWT token missing or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                unauthorizedLogout:
                  summary: JWT missing or invalid
                  value:
                    code: UNAUTHORIZED
                    message: Authentication token is missing or invalid
                    data: null
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AuthRequest:
      type: object
      properties:
        code:
          type: string
        redirectUrl:
          type: string
      required:
        - code
        - redirectUrl
    RefreshRequest:
      type: object
      properties:
        refreshToken:
          type: string
      required:
        - refreshToken
    RefreshTokenRequest:
      type: object
      properties:
        refreshToken:
          type: string
      required:
        - refreshToken
    AuthResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserView'
        accessToken:
          type: string
        tokenType:
          type: string
          example: Bearer
        expiresIn:
          type: integer
          example: 3600
        refreshToken:
          type: string
    UserView:
      type: object
      properties:
        id:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
        username:
          type: string
          example: johndoe
        email:
          type: string
          format: email
          example: johndoe@example.com
        status:
          type: string
          enum:
            - ACTIVE
            - PENDING
            - INACTIVE
          example: ACTIVE
    AuthResponseBean:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        data:
          $ref: '#/components/schemas/AuthResponse'
    UserResponseBean:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        data:
          $ref: '#/components/schemas/UserView'
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          example: INTERNAL_SERVER_ERROR
        message:
          type: string
          example: Unexpected error occurred
        data:
          nullable: true
    LogoutResponse:
      type: object
      properties:
        status:
          type: string
          example: logged_out
