openapi: 3.0.3
info:
  title: jdevtree Auth API
  description: Authentication microservice for jdevtree. Supports GitHub OAuth and local JWT auth flows.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /auth/oauth/github:
    post:
      summary: Login with GitHub
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseBean'

  /auth/oauth/github/link:
    post:
      summary: Link GitHub account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: GitHub linked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseBean'

  /auth/refresh:
    post:
      summary: Refresh access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: Token refreshed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseBean'

  /auth/logout:
    post:
      summary: Logout and revoke tokens
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: logged_out

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AuthRequest:
      type: object
      properties:
        code:
          type: string
        redirectUrl:
          type: string
      required: [code, redirectUrl]

    RefreshRequest:
      type: object
      properties:
        refreshToken:
          type: string
      required: [refreshToken]

    RefreshTokenRequest:
      type: object
      properties:
        refreshToken:
          type: string
      required: [refreshToken]

    AuthResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserView'
        accessToken:
          type: string
        tokenType:
          type: string
          example: Bearer
        expiresIn:
          type: integer
          example: 3600
        refreshToken:
          type: string

    UserView:
      type: object
      properties:
        id:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        username:
          type: string
          example: johndoe
        email:
          type: string
          format: email
          example: johndoe@example.com
        status:
          type: string
          enum: [ACTIVE, PENDING, INACTIVE]
          example: ACTIVE

    AuthResponseBean:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        data:
          $ref: '#/components/schemas/AuthResponse'

    UserResponseBean:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        data:
          $ref: '#/components/schemas/UserView'
